%all lengths are in cm
box_size = 14; 
quad_arm_length=30;
quad_arm_x=quad_arm_length*sin(pi/4);
center_to_motor_shaft=28;
quad_arm_width = 2;

quad_cross_sec = [...
    box_size/2  box_size/2-quad_arm_width/(2*sin(pi/4));...
    quad_arm_x+quad_arm_width*sin(pi/4)/2 quad_arm_x-quad_arm_width*sin(pi/4)/2;...
    quad_arm_x-quad_arm_width*sin(pi/4)/2 quad_arm_x+quad_arm_width*sin(pi/4)/2;...
    box_size/2-quad_arm_width/(2*sin(pi/4)) box_size/2 ;...
    -box_size/2+quad_arm_width/(2*sin(pi/4)) box_size/2 ;...
    -quad_arm_x+quad_arm_width*sin(pi/4)/2 quad_arm_x+quad_arm_width*sin(pi/4)/2;...
    -quad_arm_x-quad_arm_width*sin(pi/4)/2 quad_arm_x-quad_arm_width*sin(pi/4)/2;...
    -box_size/2 box_size/2-quad_arm_width/(2*sin(pi/4)) ;...
    -box_size/2 -box_size/2+quad_arm_width/(2*sin(pi/4)) ;...
    -quad_arm_x-quad_arm_width*sin(pi/4)/2 -quad_arm_x+quad_arm_width*sin(pi/4)/2;...
    -quad_arm_x+quad_arm_width*sin(pi/4)/2 -quad_arm_x-quad_arm_width*sin(pi/4)/2;...
    -box_size/2+quad_arm_width/(2*sin(pi/4)) -box_size/2 ;...
    box_size/2-quad_arm_width/(2*sin(pi/4)) -box_size/2 ;...
    quad_arm_x-quad_arm_width*sin(pi/4)/2 -quad_arm_x-quad_arm_width*sin(pi/4)/2;...
    quad_arm_x+quad_arm_width*sin(pi/4)/2 -quad_arm_x+quad_arm_width*sin(pi/4)/2;...
    box_size/2  -box_size/2+quad_arm_width/(2*sin(pi/4));...
    %box_size/2  box_size/2-quad_arm_width/(2*sin(pi/4));...
];

